# Generated by Django 5.2.1 on 2025-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_region_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='電子郵件'),
        ),
    ]
