# Generated by Django 5.2.1 on 2025-05-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_add_email_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryattraction',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120, verbose_name='預計停留時間(分鐘)'),
        ),
        migrations.AddField(
            model_name='itineraryattraction',
            name='visit_time',
            field=models.TimeField(blank=True, null=True, verbose_name='參觀時間'),
        ),
    ]
