# Generated by Django 5.2.1 on 2025-05-31 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_itineraryattraction_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itineraryattraction',
            unique_together=set(),
        ),
    ]
