# Generated by Django 5.2 on 2025-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='未命名地點', max_length=100),
            preserve_default=False,
        ),
    ]
